version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: produtosapp_sqlserver
    restart: always
    environment:
      SA_PASSWORD: "BatatinhaFrita123$"
      ACCEPT_EULA: "Y"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  mongodb:
    image: mongo:latest
    container_name: produtosapp_mongodb
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: produtosapp_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    ports:
      - "5673:5672"
      - "15673:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  mailhog:
    image: mailhog/mailhog
    container_name: produtosapp_mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  sqlserver_data:
  mongodb_data:
  rabbitmq_data:
